version: '2'
services:
  prometheus-exporter:
    image: prom/haproxy-exporter
    command:
    - --haproxy.scrape-uri=http://haproxy:8008/stats;csv
    labels:
      %{~ if affinity != "" ~}
      io.rancher.scheduler.affinity:host_label: ${affinity}
      %{~ endif ~}
      io.rancher.container.pull_image: always
      prometheus_port: '9101'
  haproxy:
    image: haproxy:1.8
    secrets:
    - source: ${name}-haproxy-config
      target: haproxy-config
    command:
    - haproxy
    - -f
    - /run/secrets/haproxy-config
    labels:
      %{~ if affinity != "" ~}
      io.rancher.scheduler.affinity:host_label: ${affinity}
      %{~ endif ~}
      io.rancher.container.pull_image: always
      %{~ if global ~}
      io.rancher.scheduler.global: 'true'
      %{~ endif ~}
secrets:
  ${name}-haproxy-config:
    external: 'true'
