version: '2'
services:
  haproxy:
    image: haproxy:2.3
    secrets:
    - ${secret}
    command:
    - haproxy
    - -f
    - /run/secrets/${secret}
    labels:
      %{~ if affinity != "" ~}
      io.rancher.scheduler.affinity:host_label: ${affinity}
      %{~ endif ~}
      io.rancher.container.pull_image: always
      %{~ if global == "true" ~}
      io.rancher.scheduler.global: 'true'
      %{~ endif ~}
      prometheus_port: '8008'
secrets:
  ${secret}:
    external: 'true'
