version: '2'
services:
  prometheus-exporter:
    scale: 1
    start_on_create: true
  haproxy:
    metadata:
      password: ${password}
      dbname: ${dbname}
      user: ${user}
      version: ${version}
    %{~ if ! global ~}
    scale: 1
    %{~ endif ~}
    start_on_create: true
