version: '2'
services:
  haproxy:
    metadata:
      password: ${password}
      dbname: ${dbname}
      user: ${user}
      version: ${version}
    %{~ if global != "true" ~}
    scale: ${scale}
    %{~ endif ~}
    start_on_create: true
